name: Build

on:
  push:
    branches:
      - master
      - rel
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Setup .NET Core 5.0.102
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102

    - name: Determine semantic version
      uses: dotnet/nbgv@master
      id: nbgv
      with:
        path: dotnet

    - name: Build
      run: dotnet build dotnet/dotnet.sln --configuration Release -p:PackageVersion=${{ steps.nbgv.outputs.SemVer2 }}

    # Uncomment to push to Github packages on a CI build from master.
    #- name: Push NuGet packages to GitHub packages
    #  if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    #  run: dotnet nuget push **/*.nupkg
    #    --source https://nuget.pkg.github.com/cyberphone/index.json
    #    --api-key ${{ secrets.GITHUB_TOKEN }}
    #    --no-symbols true
    #    --skip-duplicate

    # Uncomment to push to NuGet on a build from 'rel'
    #- name: Push NuGet packages to NuGet.org
    #  if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/rel' }}
    #  run: dotnet nuget push **/*.nupkg
    #    --source https://api.nuget.org/v3/index.json
    #    --api-key ${{ secrets.NUGET_KEY }}
    #    --no-symbols true
    #    --skip-duplicate